### ISSUE TITLE
[Bug] aad.auth.strategy managed_identity does not work with v4.0.2

### ISSUE THREAD

**Issue by jrauschenbusch** [Azure/kafka-sink-azure-kusto#105]
Managed identities do not work with kafka-sink-azure-kusto v4.0.2:

```
2023-08-14 09:52:31,203 ERROR [kusto-sink-connector-trips|task-4] Error in refreshIngestionAuthToken. 'com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder.appTokenProvider(java.util.function.Function)' (com.microsoft.azure.kusto.ingest.ResourceManager) [Timer-1]
com.microsoft.azure.kusto.ingest.exceptions.IngestionClientException: 'com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder.appTokenProvider(java.util.function.Function)'
	at com.microsoft.azure.kusto.ingest.ResourceManager.refreshIngestionAuthTokenImpl(ResourceManager.java:322)
	at com.microsoft.azure.kusto.ingest.ResourceManager.lambda$refreshIngestionAuthToken$6(ResourceManager.java:298)
	at com.microsoft.azure.kusto.data.instrumentation.MonitoredActivity.invoke(MonitoredActivity.java:33)
	at com.microsoft.azure.kusto.data.instrumentation.MonitoredActivity.invoke(MonitoredActivity.java:26)
	at com.microsoft.azure.kusto.ingest.ResourceManager.refreshIngestionAuthToken(ResourceManager.java:297)
	at com.microsoft.azure.kusto.ingest.ResourceManager.access$500(ResourceManager.java:41)
	at com.microsoft.azure.kusto.ingest.ResourceManager$1RefreshIngestionAuthTokenTask.run(ResourceManager.java:147)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: java.lang.NoSuchMethodError: 'com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder.appTokenProvider(java.util.function.Function)'
	at com.azure.identity.implementation.IdentityClientBase.getManagedIdentityConfidentialClient(IdentityClientBase.java:348)
	at com.azure.identity.implementation.IdentityClient.lambda$getManagedIdentityConfidentialClientApplication$2(IdentityClient.java:132)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4382)
	at reactor.core.publisher.Mono.block(Mono.java:1706)
	at com.microsoft.azure.kusto.data.auth.ManagedIdentityTokenProvider.acquireAccessTokenImpl(ManagedIdentityTokenProvider.java:44)
	at com.microsoft.azure.kusto.data.instrumentation.MonitoredActivity.invoke(MonitoredActivity.java:33)
	at com.microsoft.azure.kusto.data.auth.TokenProviderBase.acquireAccessToken(TokenProviderBase.java:32)
	at com.microsoft.azure.kusto.data.ClientImpl.generateIngestAndCommandHeaders(ClientImpl.java:365)
	at com.microsoft.azure.kusto.data.ClientImpl.executeToJsonResult(ClientImpl.java:174)
	at com.microsoft.azure.kusto.data.ClientImpl.executeImpl(ClientImpl.java:134)
	at com.microsoft.azure.kusto.data.ClientImpl.lambda$execute$0(ClientImpl.java:115)
	at com.microsoft.azure.kusto.data.instrumentation.MonitoredActivity.invoke(MonitoredActivity.java:33)
	at com.microsoft.azure.kusto.data.ClientImpl.execute(ClientImpl.java:114)
	at com.microsoft.azure.kusto.data.ClientImpl.execute(ClientImpl.java:108)
	at com.microsoft.azure.kusto.data.ClientImpl.execute(ClientImpl.java:103)
	at com.microsoft.azure.kusto.ingest.ResourceManager.lambda$refreshIngestionAuthTokenImpl$e961bae5$1(ResourceManager.java:308)
	at io.github.resilience4j.retry.Retry.lambda$decorateCheckedSupplier$3f69f149$1(Retry.java:137)
	at com.microsoft.azure.kusto.ingest.ResourceManager.refreshIngestionAuthTokenImpl(ResourceManager.java:309)
	... 8 more
```

There is a mismatch of MSAL dependency in kusto-data:5.0.0 (msal:1.9.0) and azure-identity:1.9.0 (msal:1.13.8):

References:
- https://github.com/Azure/azure-kusto-java/blob/v5.0.0/pom.xml#L39
- https://github.com/Azure/azure-kusto-java/blob/v5.0.0/pom.xml#L47
- https://github.com/Azure/azure-sdk-for-java/blob/azure-sdk-bom_1.2.13/sdk/boms/azure-sdk-bom/pom.xml#L163-L167
- https://github.com/Azure/azure-sdk-for-java/blob/azure-identity_1.9.0/sdk/identity/azure-identity/pom.xml#L43-L46

There is already a patch available coming with https://github.com/Azure/azure-kusto-java/releases/tag/v5.0.1.

**Comment by ag-ramachandran** [comment]
Hello @jrauschenbusch , We'll get a new release drafted in the next couple of days and get this fixed. Thanks for reporting the issue

**Comment by ag-ramachandran** [comment]
Hello @jrauschenbusch. A new release is available at : https://github.com/Azure/kafka-sink-azure-kusto/releases/tag/v4.0.3

This will be in confluent store in the next day or so. Please give it a try when you get sometime and let us know

**Comment by ag-ramachandran** [comment]
Closing issue as it is resolved
